# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
nama: CI

pada: alur kerja_dispatch

pekerjaan:

  membangun:

    berjalan-on: windows-terbaru

    menit-waktu habis: 9999

    Langkah:

    - Nama : Download Ngrok & NSSM

      lari: |
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/nssm.exe -OutFile nssm.exe
    - nama: Salin NSSM & Ngrok ke Direktori Windows.

      lari: | 
        salin nssm.exe C:\Windows\System32
        salin ngrok.exe C:\Windows\System32
    - nama: Hubungkan akun NGROK Anda

      jalankan: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      lingkungan:

        NGROK_AUTH_TOKEN: ${{ rahasia.NGROK_AUTH_TOKEN }}

    - nama: Unduh File Penting.

      lari: |
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/avgchamara/WindowsRDP/raw/main/loop.bat -OutFile loop.bat
    - nama: Buat file YML untuk NGROK.

      jalankan: mulai NGROK-AP.bat

    - nama: Aktifkan Akses RDP.

      lari: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-nama "fDenyTSConnections" -Nilai 0
        Aktifkan-NetFirewallRule -DisplayGroup "Desktop Jarak Jauh"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -nama "UserAuthentication" -Nilai 1
    - nama: Buat Terowongan

      jalankan: sc start ngrok

    - nama: Hubungkan ke Ram RDP 2core-7GB Anda.

      jalankan: cmd /c NGROK-CHECK.bat

    - nama: Semua Selesai! Anda dapat menutup Tab sekarang! Waktu VM maksimum: 6 jam.

      jalankan: cmd /c loop.bat
